## Setting Up and Importing Libraries
In this step, we'll import the necessary libraries and modules. We'll also ensure the correct path is set to access our custom modules.

In [1]:
# Import necessary libraries
import pandas as pd
import os
import sys
import json

In [2]:
# Going back to the root directory to make sure that we execute from codice folder
os.chdir(os.path.join(os.getcwd(), '..'))
print(os.getcwd())

/home/rita/TRUST_AI/trustframework/trustCE

In [3]:
from codice.cfsearch import CFsearch
from codice.dataset import Dataset
from codice.cemodels.base_model import BaseModel
from codice.cemodels.sklearn_model import SklearnModel
from codice.ceinstance.instance_sampler import CEInstanceSampler
from codice.config import Config
from codice.transformer import Transformer
from codice.ceinstance.instance_factory import InstanceFactory
from codice import load_datasets

## Loading Configuration
Here, we'll load our configuration files which dictate various parameters for our counterfactual search. It includes dataset details, feature management, and other related configurations.

In [4]:
# Load configuration
config_file_path = "config/homeloan/conf_homeloan_coherence.yaml"
config = Config(config_file_path)

with open("config/homeloan/constraints_homeloan_ch.json", 'r') as file:
    constraints = json.load(file)

print("Configuration Loaded:")
print(config)

Configuration Loaded:
<codice.config.Config object at 0x70f8818e4610>

## Preparing Dataset and Model
In this section, we initialize our dataset, model, and the required transformers. We'll also define a sample instance for which we wish to find the counterfactuals.

In [5]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
import pickle

In [6]:
# Loading dataset and trianing model
input=pd.read_csv('datasets/homeloan_oredered_features.csv',sep=',')

input["Loan_Status"] = input["Loan_Status"].astype('int')

continuous_features_list = ['ApplicantIncome','CoapplicantIncome','LoanAmount', 'Loan_Amount_Term', 'Credit_History']
categorical_features_list = ['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed', 'Property_Area']

X=input.copy().drop(["Loan_Status"], axis=1)
y=input.copy()["Loan_Status"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)
# Create transformers for continuous and categorical features
continuous_transformer = Pipeline(steps=[
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

# Get the indices of continuous and categorical features
get_index_number_of_cont_features = [X.columns.get_loc(c) for c in continuous_features_list if c in X]
get_index_number_of_cat_features = [X.columns.get_loc(c) for c in categorical_features_list if c in X]

# Create the ColumnTransformer to apply the transformations to the correct columns in the dataframe
preprocessor = ColumnTransformer(
    transformers=[
        ('num', continuous_transformer, get_index_number_of_cont_features),
        ('cat', categorical_transformer, get_index_number_of_cat_features)
    ])
# Create the full pipeline
model_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression(max_iter=1000))
])

model_pipeline.fit(X_train, y_train)
# Check the accuracy of the model
print("Accuracy on training set: ", model_pipeline.score(X_train, y_train))
print("Accuracy on test set: ", model_pipeline.score(X_test, y_test))
# Save the model to models/homeloan_logistic_model.pkl
with open("models/homeloan_logistic_model_notebook.pkl", 'wb') as file:
    pickle.dump(model_pipeline, file)

Accuracy on training set:  0.8115384615384615
Accuracy on test set:  0.8275862068965517

### Initializing CoDiCE Dataset and Model

In [7]:
data = Dataset(config.get_config_value("dataset"), "Loan_Status")
normalization_transformer = Transformer(data, config)
instance_factory = InstanceFactory(data)
sampler = CEInstanceSampler(config, normalization_transformer, instance_factory)

model = BaseModel(config.get_config_value("model"), model_pipeline)

2025-06-08 00:52:59,073 - codice.dataset - INFO - Loading dataset from datasets/homeloan_oredered_features.csv
2025-06-08 00:52:59,084 - codice.dataset - INFO - Loaded 5 continuous and 6 categorical features
2025-06-08 00:52:59,093 - codice.dataset - INFO - Features verified
2025-06-08 00:52:59,095 - codice.dataset - INFO - Preprocessing dataset
2025-06-08 00:52:59,109 - codice.dataset - INFO - Dataset preprocessed
2025-06-08 00:52:59,841 - codice.transformer - WARNING - MAD for feature Loan_Amount_Term is 0, replaced with 1.0 to avoid error.
2025-06-08 00:52:59,842 - codice.transformer - WARNING - MAD for feature Credit_History is 0, replaced with 1.0 to avoid error.

## Finding Counterfactuals
With everything set up, we'll now search for counterfactuals for our sample instance using the CFsearch object.

In [8]:
# Set the target instance path
target_instance_json = "input_instance/homeloan/instance_homeloan.json"

In [9]:
# Create a CFsearch object
config_for_cfsearch = config.get_config_value("cfsearch")
search = CFsearch(normalization_transformer, model, sampler, config,
                  optimizer_name=config_for_cfsearch["optimizer"], 
                  distance_continuous=config_for_cfsearch["continuous_distance"], 
                  distance_categorical=config_for_cfsearch["categorical_distance"], 
                  loss_type=config_for_cfsearch["loss_type"], 
                  coherence=config_for_cfsearch["coherence"],
                  objective_function_weights=config_for_cfsearch["objective_function_weights"])

# Load target instance and find counterfactuals
with open(target_instance_json, 'r') as file:
    target_instance_json_content = file.read()

target_instance = instance_factory.create_instance_from_json(target_instance_json_content)

In [10]:
counterfactuals = search.find_counterfactuals(target_instance, number_cf=1, desired_class="opposite", maxiterations=50)

2025-06-08 00:52:59,869 - codice.cfsearch - INFO - Finding counterfactuals for instance: {'Gender': 'Male', 'Married': 'Yes', 'Dependents': '2', 'Education': 'Graduate', 'Self_Employed': 'No', 'Property_Area': 'Urban', 'ApplicantIncome': 4616, 'CoapplicantIncome': 0.0, 'LoanAmount': 134.0, 'Loan_Amount_Term': 360, 'Credit_History': 1.0}
2025-06-08 00:53:17,411 - codice.cfsearch - INFO - Valid counterfactual found: {'Gender': 'Male', 'Married': 'Yes', 'Dependents': '2', 'Education': 'Graduate', 'Self_Employed': 'No', 'Property_Area': 'Urban', 'ApplicantIncome': 20464.438387055292, 'CoapplicantIncome': 35764.21345416311, 'LoanAmount': 606.206942157842, 'Loan_Amount_Term': 23.541796683082083, 'Credit_History': 0.17245298863785863}

## Evaluation and Visualization
Once the counterfactuals are generated, it's crucial to evaluate and visualize them. This helps in understanding how the counterfactuals differ from the original instance and assessing their quality.

In [13]:
# Evaluate and visualize the counterfactuals
search.evaluate_counterfactuals(target_instance, counterfactuals)

# Display the counterfactuals and original instance in the notebook
display_df = search.visualize_as_dataframe(target_instance, counterfactuals)

2025-06-08 00:53:30,309 - codice.cfsearch - INFO - Query instance (original outcome : 1)

,Gender,Married,Dependents,Education,Self_Employed,Property_Area,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
0,Male,Yes,2,Graduate,No,Urban,4616,0.0,134.0,360,1.0

2025-06-08 00:53:30,317 - codice.cfsearch - INFO -
Counterfactual set (new outcome: [array([0])])

,Gender,Married,Dependents,Education,Self_Employed,Property_Area,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
0,-,-,-,-,-,-,20464.438387055292,35764.21345416311,606.206942157842,23.541796683082083,0.17245298863785863

## Storing the Results
For reproducibility and further analysis, we'll store the counterfactuals and their evaluations in designated folders.

In [12]:
# Store results
search.store_counterfactuals(config.get_config_value("output_folder"), "homeloan_first_test")
search.store_evaluations(config.get_config_value("output_folder"), "homeloan_first_eval")

2025-06-08 00:53:17,464 - codice.cfsearch - INFO - Store counterfactuals to results/homeloan_first_test_0.json
2025-06-08 00:53:17,466 - codice.cfsearch - INFO - Store counterfactuals evaluation to results/homeloan_first_eval_eval_0.json